name: Linkstr
options:
  deploymentTarget:
    iOS: 17.0
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.10
packages:
  NostrSDK:
    url: https://github.com/nostr-sdk/nostr-sdk-ios.git
    branch: main
schemes:
  Linkstr:
    build:
      targets:
        Linkstr: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: LinkstrTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
targets:
  Linkstr:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - path: LinkstrApp
    dependencies:
      - package: NostrSDK
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.parmscript.linkstr
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_ENTITLEMENTS: LinkstrApp/Linkstr.entitlements
        CODE_SIGN_IDENTITY: Apple Development
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_FILE: LinkstrApp/Info.plist
        DEVELOPMENT_TEAM: "7654L3CX5L"
    info:
      path: LinkstrApp/Info.plist
      properties:
        CFBundleDisplayName: linkstr
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        NSCameraUsageDescription: Camera access is used to scan Contact Key (npub) QR codes.
        UILaunchStoryboardName: LaunchScreen
        NSAppTransportSecurity:
          NSAllowsArbitraryLoadsInWebContent: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleURLTypes:
          - CFBundleURLName: com.parmscript.linkstr.deeplink
            CFBundleURLSchemes:
              - linkstr

  LinkstrTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - path: LinkstrTests
    dependencies:
      - target: Linkstr
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
